// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type DashboardDocumentDataSlicesSlice =
  | TopCreatorSectionSlice
  | CollectionSectionSlice
  | AboutSlice
  | LogoSectionSlice
  | HeroSlice;

/**
 * Content for dashboard documents
 */
interface DashboardDocumentData {
  /**
   * Slice Zone field in *dashboard*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: dashboard.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<DashboardDocumentDataSlicesSlice>; /**
   * Meta Title field in *dashboard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: dashboard.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *dashboard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: dashboard.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *dashboard*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dashboard.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * dashboard document from Prismic
 *
 * - **API ID**: `dashboard`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DashboardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DashboardDocumentData>,
    "dashboard",
    Lang
  >;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Search Placeholder field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.search_placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  search_placeholder: prismic.KeyTextField;

  /**
   * Wallet Text field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.wallet_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  wallet_text: prismic.KeyTextField;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = DashboardDocument | SettingsDocument;

/**
 * Primary content in *AboutSection → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * title field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * about_image field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.about_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  about_image: prismic.ImageField<never>;

  /**
   * heading field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * description field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * show_button field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: about.default.primary.show_button
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_button: prismic.BooleanField;

  /**
   * button_text field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutSection*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Item in *CollectionSection → Default → Primary → items*
 */
export interface CollectionSectionSliceDefaultPrimaryItemsItem {
  /**
   * nft_image field in *CollectionSection → Default → Primary → items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_section.default.primary.items[].nft_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  nft_image: prismic.ImageField<never>;

  /**
   * nft_title field in *CollectionSection → Default → Primary → items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_section.default.primary.items[].nft_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nft_title: prismic.KeyTextField;

  /**
   * author field in *CollectionSection → Default → Primary → items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_section.default.primary.items[].author
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * bid field in *CollectionSection → Default → Primary → items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_section.default.primary.items[].bid
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  bid: prismic.KeyTextField;

  /**
   * Button Text field in *CollectionSection → Default → Primary → items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_section.default.primary.items[].button_text
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  button_text: prismic.SelectField<"Sport" | "Photograpy" | "Pattern">;
}

/**
 * Item in *CollectionSection → featured  → Primary → items*
 */
export interface CollectionSectionSliceFeaturedPrimaryItemsItem {
  /**
   * nft_image field in *CollectionSection → featured  → Primary → items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_section.featured.primary.items[].nft_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  nft_image: prismic.ImageField<never>;

  /**
   * nft_title field in *CollectionSection → featured  → Primary → items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_section.featured.primary.items[].nft_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nft_title: prismic.KeyTextField;

  /**
   * author field in *CollectionSection → featured  → Primary → items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_section.featured.primary.items[].author
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * bid field in *CollectionSection → featured  → Primary → items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_section.featured.primary.items[].bid
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  bid: prismic.KeyTextField;

  /**
   * Button Text field in *CollectionSection → featured  → Primary → items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_section.featured.primary.items[].button_text
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  button_text: prismic.SelectField<"Sport" | "Photograpy" | "Pattern">;
}

/**
 * Primary content in *CollectionSection → Default → Primary*
 */
export interface CollectionSectionSliceDefaultPrimary {
  /**
   * title field in *CollectionSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *CollectionSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * show_tabs field in *CollectionSection → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: collection_section.default.primary.show_tabs
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_tabs: prismic.BooleanField;

  /**
   * items field in *CollectionSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<CollectionSectionSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for CollectionSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CollectionSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CollectionSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CollectionSection → featured  → Primary*
 */
export interface CollectionSectionSliceFeaturedPrimary {
  /**
   * title field in *CollectionSection → featured  → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_section.featured.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *CollectionSection → featured  → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_section.featured.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * show_tabs field in *CollectionSection → featured  → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: collection_section.featured.primary.show_tabs
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_tabs: prismic.BooleanField;

  /**
   * items field in *CollectionSection → featured  → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_section.featured.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<CollectionSectionSliceFeaturedPrimaryItemsItem>
  >;

  /**
   * category field in *CollectionSection → featured  → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_section.featured.primary.category
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<"featured" | "featured">;
}

/**
 * featured  variation for CollectionSection Slice
 *
 * - **API ID**: `featured`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CollectionSectionSliceFeatured = prismic.SharedSliceVariation<
  "featured",
  Simplify<CollectionSectionSliceFeaturedPrimary>,
  never
>;

/**
 * Slice variation for *CollectionSection*
 */
type CollectionSectionSliceVariation =
  | CollectionSectionSliceDefault
  | CollectionSectionSliceFeatured;

/**
 * CollectionSection Shared Slice
 *
 * - **API ID**: `collection_section`
 * - **Description**: CollectionSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CollectionSectionSlice = prismic.SharedSlice<
  "collection_section",
  CollectionSectionSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Buttons*
 */
export interface HeroSliceDefaultPrimaryButtonsItem {
  /**
   * Button Text field in *Hero → Default → Primary → Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[].button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   *  Button Link field in *Hero → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[].button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   *  Button Type field in *Hero → Default → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[].button_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  button_type: prismic.SelectField<"primary" | "secondary">;
}

/**
 * Item in *Hero → Default → Primary → stats*
 */
export interface HeroSliceDefaultPrimaryStatsItem {
  /**
   * Number field in *Hero → Default → Primary → stats*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.stats[].number
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  number: prismic.NumberField;

  /**
   * Label field in *Hero → Default → Primary → stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.stats[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Hero Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Buttons field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryButtonsItem>>;

  /**
   * stats field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  stats: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *LogoSection → Default → Primary → logos*
 */
export interface LogoSectionSliceDefaultPrimaryLogosItem {
  /**
   * LogoSection field in *LogoSection → Default → Primary → logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_section.default.primary.logos[].logosection
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logosection: prismic.ImageField<never>;

  /**
   * alt_text field in *LogoSection → Default → Primary → logos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_section.default.primary.logos[].alt_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  alt_text: prismic.KeyTextField;

  /**
   * size field in *LogoSection → Default → Primary → logos*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_section.default.primary.logos[].size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"default" | "big" | "small">;
}

/**
 * Primary content in *LogoSection → Default → Primary*
 */
export interface LogoSectionSliceDefaultPrimary {
  /**
   * logos field in *LogoSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_section.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  logos: prismic.GroupField<Simplify<LogoSectionSliceDefaultPrimaryLogosItem>>;
}

/**
 * Default variation for LogoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogoSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LogoSection*
 */
type LogoSectionSliceVariation = LogoSectionSliceDefault;

/**
 * LogoSection Shared Slice
 *
 * - **API ID**: `logo_section`
 * - **Description**: LogoSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoSectionSlice = prismic.SharedSlice<
  "logo_section",
  LogoSectionSliceVariation
>;

/**
 * Item in *TopCreatorSection → Default → Primary → creators*
 */
export interface TopCreatorSectionSliceDefaultPrimaryCreatorsItem {
  /**
   * Image field in *TopCreatorSection → Default → Primary → creators*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: top_creator_section.default.primary.creators[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * background image field in *TopCreatorSection → Default → Primary → creators*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: top_creator_section.default.primary.creators[].background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * author field in *TopCreatorSection → Default → Primary → creators*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_creator_section.default.primary.creators[].author
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * text field in *TopCreatorSection → Default → Primary → creators*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_creator_section.default.primary.creators[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * followed field in *TopCreatorSection → Default → Primary → creators*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: top_creator_section.default.primary.creators[].followed
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  followed: prismic.BooleanField;
}

/**
 * Primary content in *TopCreatorSection → Default → Primary*
 */
export interface TopCreatorSectionSliceDefaultPrimary {
  /**
   * title field in *TopCreatorSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_creator_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *TopCreatorSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_creator_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * creators field in *TopCreatorSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: top_creator_section.default.primary.creators[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  creators: prismic.GroupField<
    Simplify<TopCreatorSectionSliceDefaultPrimaryCreatorsItem>
  >;
}

/**
 * Default variation for TopCreatorSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TopCreatorSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TopCreatorSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TopCreatorSection*
 */
type TopCreatorSectionSliceVariation = TopCreatorSectionSliceDefault;

/**
 * TopCreatorSection Shared Slice
 *
 * - **API ID**: `top_creator_section`
 * - **Description**: TopCreatorSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TopCreatorSectionSlice = prismic.SharedSlice<
  "top_creator_section",
  TopCreatorSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DashboardDocument,
      DashboardDocumentData,
      DashboardDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      CollectionSectionSlice,
      CollectionSectionSliceDefaultPrimaryItemsItem,
      CollectionSectionSliceDefaultPrimary,
      CollectionSectionSliceFeaturedPrimaryItemsItem,
      CollectionSectionSliceFeaturedPrimary,
      CollectionSectionSliceVariation,
      CollectionSectionSliceDefault,
      CollectionSectionSliceFeatured,
      HeroSlice,
      HeroSliceDefaultPrimaryButtonsItem,
      HeroSliceDefaultPrimaryStatsItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      LogoSectionSlice,
      LogoSectionSliceDefaultPrimaryLogosItem,
      LogoSectionSliceDefaultPrimary,
      LogoSectionSliceVariation,
      LogoSectionSliceDefault,
      TopCreatorSectionSlice,
      TopCreatorSectionSliceDefaultPrimaryCreatorsItem,
      TopCreatorSectionSliceDefaultPrimary,
      TopCreatorSectionSliceVariation,
      TopCreatorSectionSliceDefault,
    };
  }
}
