// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./AboutSection")),
  collection_section: dynamic(() => import("./CollectionSection")),
  faq_section: dynamic(() => import("./FaqSection")),
  footer_section: dynamic(() => import("./FooterSection")),
  hero: dynamic(() => import("./Hero")),
  logo_section: dynamic(() => import("./LogoSection")),
  nft_section: dynamic(() => import("./NftSection")),
  top_creator_section: dynamic(() => import("./TopCreatorSection")),
};
