// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./AboutSection")),
  collection_section: dynamic(() => import("./CollectionSection")),
  hero: dynamic(() => import("./Hero")),
  logo_section: dynamic(() => import("./LogoSection")),
  top_creator_section: dynamic(() => import("./TopCreatorSection")),
};
